name: Style Guidelines

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: npm i -g eslint
    - name: Style Test game.js
      run: eslint src/game.js
    - name: Style Test gameconfig.js
      run: eslint src/gameconfig.js
    - name: Style Test engine.js
      run: eslint engine.js